# Generated by Django 5.0.1 on 2024-01-16 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_remove_profesor_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='CursoID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notas.curso'),
        ),
    ]
